---
os: linux
dist: bionic
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.7
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
jobs:
  fast_finish: true
  include:
    -
      env: CHECK="validate lint check rubocop"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.7
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - main
    - /^v\d/
notifications:
  email: false
