---
dist: jammy
os: linux
language: ruby
cache: bundler

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

matrix:
  include:
  - rvm: 2.5
    env: VERSION='~> 5.5.22'
  - rvm: 2.7
    env: VERSION='~> 6.28.0'
  - rvm: 3.1
    env: VERSION='~> 7.23.0'

# execute tests
install:
- gem install --no-document -v "$VERSION" puppet
- gem install --no-document puppet-check
before_script: puppet --version
script: puppet-check -s .
