---
version: 2.1

jobs:
  test:
    parameters:
      puppet_version:
        type: string
    working_directory: /tmp/extended_stdlib
    docker:
    - image: puppet/pdk:latest
    steps:
    - checkout
    - run:
        name: create empty templates dir for script unit test
        command: mkdir templates
    - run:
        name: execute unit tests
        command: pdk test unit --puppet-version << parameters.puppet_version >>

workflows:
  execute_tests:
    jobs:
    - test:
        matrix:
          parameters:
            puppet_version:
            - '6.28.0'
            - '7.22.0'
