---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '**.pp'
    - '**.rb'
  pull_request:
    branches: [master]
    paths:
    - '**.pp'
    - '**.rb'

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: matthewschuchard/puppet-check
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: execute checks
      run: puppet-check -s .
