---
name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        container: ['matthewschuchard/puppet-check:latest']
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: execute checks
      run: puppet-check -s .
